[build]
  base = "apps/web"
  command = "cd ../.. && npm install -g pnpm && pnpm install && cd apps/web && pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
