[build]
  base = "apps/web"
  command = "cd ../.. && pnpm install && pnpm build"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "9.0.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"
